### ISSUE TITLE
Jekyll--rebuild task is not defined

### ISSUE THREAD

**Issue by glenncoppens** [getchopstick/fork-starter-workflow#2]
Hi

Being new to all these frontend development tools I also discovered yesterday that, when doing `gulp watch` and modifying some files, it fires the `jekyl--rebuild` task defined in `tasks/watch.js`. 
This generates an error, which says that this `jekyll--rebuild` task does not exist. Obvious, because there is nog jekyll task in the tasks folder, like you have in the Chopstick boilerplate. 

Might be a little bug, because I guess you didn't want jekyll to be required in this repo right? Then the jekyll--rebuild task in watch.js can be safely removed?

G.

**Comment by JonasDeGeest** [comment]
That's correct. The Jekyll build task is unnecessary in this workflow. This issue is fixed.
